---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: "8u171-jdk-stretch"

inputs:
  - name: source-code

outputs:
  - name: build-output

run:
  path: source-code/ci/build.sh
